# Example catalog-info.yaml entity definition file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azuredevops
  description: azure devops cicd
  # ...
  annotations:
    dev.azure.com/project-repo: DevSecOpsSRE/azuredevops
spec:
  type: service
  # ...
