apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Jenkins'
  description: 'Monitor Jenkins CICD'
  annotations:
    jenkins.io/job-full-name: 'Backstage/sample_jenkins' # use this instead
spec:
  type: service
  lifecycle: experimental
  owner: your-name
