apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'Jenkins'
  description: 'Monitor Jenkins CICD'
  annotations:
    jenkins.io/job-full-name: 'jenkins-maven-pipeline' # use this instead
    sonarqube.org/project-key: MyOrgBackstage_springboot-maven-micro
spec:
  type: service
  lifecycle: experimental
  owner: your-name
