apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-service-api
  description: API for My Service
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    openapi: 3.0.0
    info:
      title: My Service API
      version: 1.0.0
    paths: {}
