apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'My-App'
  description: 'Demo Java app'
  annotations:
    jenkins.io/job-full-name: 'jenkins-maven-pipeline' # use this instead
    sonarqube.org/project-key: MyOrgBackstage_springboot-maven-micro
    jira/project-key: DEV
    backstage.io/techdocs-ref: dir:.
    # mandatory annotation
    harness.io/project-url: https://app.harness.io/ng/account/yEWJldNeS3aMf9whDHiY-A/all/orgs/default/projects/default_project/overview
    # optional annotations, don't include this block if not needed. Add this if specific pipeline executions needs to be shown on the Plugin. When specified, latest pipeline execution details for configured pipelineIds(max 10) and configured serviceId will be shown.
    #  harness.io/ci-pipelineIds: <pipelineId1,pipelineId2,pipelineId3 etc>
   # harness.io/cd-serviceId: <serviceId>
  links:  
    - url: https://github.com/my-org/my-service
      title: GitHub Repo
      icon: github
    - url: https://my-service.docs.com
      title: Documentation
      icon: docs
    - url: https://my-service.run.com
      title: Live Site
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: your-name
